"""Core Reddit automation analysis services shared by multiple entrypoints."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import time
from typing import Any, Dict, Iterator, List, Sequence, Type, TypeVar

import praw
from openai import OpenAI
from pydantic import BaseModel, Field, ValidationError

from src.infra.observability import TelemetryRecorder


T = TypeVar("T", bound=BaseModel)


class InitialAssessment(BaseModel):
    """Structured output for the initial title-only screen."""

    is_automation: bool = Field(
        ...,
        description=(
            "True when the post likely relates to an automation or agent use "
            "case that merits deeper analysis."
        ),
    )
    rationale: str = Field(..., description="Brief justification for the decision.")


class AutomationInsight(BaseModel):
    """Structured output for the full deep-dive analysis."""

    automation_summary: str
    deep_analysis: str
    automation_complexity: str
    required_tools: List[str] = Field(default_factory=list)


class PostReport(BaseModel):
    """Final report entry generated by the analyzer."""

    submission_id: str
    subreddit: str
    title: str
    url: str
    permalink: str
    created: str
    created_utc: datetime
    score: int
    num_comments: int
    initial_assessment: InitialAssessment
    automation_insight: AutomationInsight


class AnalysisReport(BaseModel):
    """Container for a full automation analysis run."""

    generated_at: str
    query: str
    time_filter: str
    posts: List[PostReport] = Field(default_factory=list)

    @property
    def total_posts(self) -> int:
        return len(self.posts)


@dataclass
class AnalyzerDependencies:
    reddit: praw.Reddit
    openai: OpenAI
    openai_model: str
    prompts: Dict[str, str]
    telemetry: TelemetryRecorder | None = None


def _parse_as_model(
    client: OpenAI,
    *,
    model: str,
    prompt: str,
    text_format: Type[T],
    telemetry: TelemetryRecorder | None = None,
    prompt_label: str | None = None,
) -> T:
    if telemetry:
        telemetry.log_openai_request(prompt_label=prompt_label)
    start = time.perf_counter()
    response = client.responses.parse(
        model=model,
        input=[{"role": "user", "content": prompt}],
        max_output_tokens=400,
        text_format=text_format,
    )
    duration_ms = (time.perf_counter() - start) * 1000
    usage_payload = _extract_usage(response)
    if telemetry:
        telemetry.log_openai_response(
            prompt_label=prompt_label,
            duration_ms=duration_ms,
            usage=usage_payload,
        )
    if isinstance(response, text_format):
        return response

    parsed_payload = getattr(response, "parsed", None)
    if isinstance(parsed_payload, text_format):
        return parsed_payload
    if parsed_payload is not None:
        return text_format.model_validate(parsed_payload)

    output_parsed = getattr(response, "output_parsed", None)
    if isinstance(output_parsed, text_format):
        return output_parsed
    if output_parsed is not None:
        return text_format.model_validate(output_parsed)

    output_items = getattr(response, "output", None)
    if output_items is not None:
        for item in output_items:
            content_list = getattr(item, "content", None)
            if content_list is None:
                continue
            for content in content_list:
                parsed_value = getattr(content, "parsed", None)
                if isinstance(parsed_value, text_format):
                    return parsed_value
                if parsed_value is not None:
                    return text_format.model_validate(parsed_value)
    if hasattr(response, "model_dump"):
        dumped = response.model_dump()
        if isinstance(dumped, dict):
            try:
                return text_format.model_validate(dumped)
            except ValidationError:
                pass

    raise ValidationError(
        [
            {
                "type": "model_parsing",
                "loc": (text_format.__name__,),
                "msg": "Unable to locate parsed content in OpenAI response.",
                "input": response,
            }
        ],
        model=text_format,
    )


def _extract_usage(response: Any) -> Dict[str, Any] | None:
    usage = getattr(response, "usage", None)
    if usage is None:
        return None
    if isinstance(usage, dict):
        return usage
    if hasattr(usage, "model_dump"):
        payload = usage.model_dump()
        if isinstance(payload, dict):
            return payload
    snapshot: Dict[str, Any] = {}
    for key in (
        "prompt_tokens",
        "completion_tokens",
        "input_tokens",
        "output_tokens",
        "total_tokens",
    ):
        value = getattr(usage, key, None)
        if value is not None:
            snapshot[key] = value
    return snapshot or None


def _truncate(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return f"{text[:limit]}..."


def summarize_post(post: praw.models.Submission) -> Dict[str, Any]:
    return {
        "id": post.id,
        "subreddit": str(post.subreddit),
        "title": post.title,
        "url": f"https://www.reddit.com{post.permalink}",
        "permalink": post.permalink,
        "created_utc": post.created_utc,
        "score": post.score,
        "num_comments": post.num_comments,
    }


def search_posts(
    reddit_client: praw.Reddit,
    *,
    subreddits: Sequence[str],
    query: str,
    time_filter: str,
    limit: int,
    telemetry: TelemetryRecorder | None = None,
) -> Iterator[Dict[str, Any]]:
    for subreddit_name in subreddits:
        subreddit = reddit_client.subreddit(subreddit_name)
        metadata = {
            "subreddit": subreddit_name,
            "query": query,
            "time_filter": time_filter,
            "limit": limit,
        }
        if telemetry:
            telemetry.log_reddit_call(
                action="search",
                phase="start",
                metadata=metadata,
            )
        start = time.perf_counter()
        total = 0
        for submission in subreddit.search(
            query, sort="new", time_filter=time_filter, limit=limit
        ):
            total += 1
            yield summarize_post(submission)
        duration_ms = (time.perf_counter() - start) * 1000
        if telemetry:
            telemetry.log_reddit_call(
                action="search",
                phase="finish",
                metadata={**metadata, "post_count": total},
                duration_ms=duration_ms,
                quota=_reddit_quota_snapshot(reddit_client),
            )


def fetch_full_post(
    reddit_client: praw.Reddit,
    url_or_id: str,
    *,
    max_comments: int,
    telemetry: TelemetryRecorder | None = None,
) -> Dict[str, Any]:
    metadata = {"submission": url_or_id, "max_comments": max_comments}
    if telemetry:
        telemetry.log_reddit_call(
            action="fetch_submission",
            phase="start",
            metadata=metadata,
        )
    start = time.perf_counter()
    if url_or_id.startswith("http"):
        submission = reddit_client.submission(url=url_or_id)
    else:
        submission = reddit_client.submission(id=url_or_id)

    post = {
        "id": submission.id,
        "subreddit": str(submission.subreddit),
        "title": submission.title,
        "selftext": submission.selftext,
        "author": str(submission.author) if submission.author else None,
        "created_utc": submission.created_utc,
        "score": submission.score,
        "url": submission.url,
        "is_self": submission.is_self,
        "num_comments": submission.num_comments,
        "media": submission.media,
    }

    submission.comments.replace_more(limit=0)
    comments = []
    for index, comment in enumerate(submission.comments.list()):
        if max_comments >= 0 and index >= max_comments:
            break
        comments.append(
            {
                "id": comment.id,
                "author": str(comment.author) if comment.author else None,
                "body": comment.body,
                "created_utc": comment.created_utc,
                "score": comment.score,
                "parent_id": comment.parent_id,
            }
        )

    post["comments"] = comments
    if telemetry:
        telemetry.log_reddit_call(
            action="fetch_submission",
            phase="finish",
            metadata={**metadata, "comment_count": len(comments)},
            duration_ms=(time.perf_counter() - start) * 1000,
            quota=_reddit_quota_snapshot(reddit_client),
        )
    return post


def _reddit_quota_snapshot(reddit_client: praw.Reddit) -> Dict[str, Any] | None:
    auth = getattr(reddit_client, "auth", None)
    limits = getattr(auth, "limits", None)
    if limits is None:
        return None
    snapshot: Dict[str, Any] = {}
    keys = ("used", "remaining", "reset_timestamp")
    if isinstance(limits, dict):
        for key in keys:
            if key in limits:
                snapshot[key] = limits[key]
    else:
        for key in keys:
            value = getattr(limits, key, None)
            if value is not None:
                snapshot[key] = value
    return snapshot or None


class AutomationAnalyzer:
    def __init__(self, deps: AnalyzerDependencies) -> None:
        self._reddit = deps.reddit
        self._openai = deps.openai
        self._model = deps.openai_model
        self._prompts = deps.prompts
        self._telemetry = deps.telemetry

    def initial_assessment(self, post_summary: Dict[str, Any]) -> InitialAssessment:
        post_details = (
            f"Subreddit: {post_summary['subreddit']}\n"
            f"Title: {post_summary['title']}\n"
            f"Score: {post_summary['score']}\n"
            f"Comments: {post_summary['num_comments']}\n"
            f"Permalink: {post_summary['url']}"
        )
        prompt = (
            f"{self._prompts['initial_assessment']}\n\n"
            "Return structured data with fields is_automation (boolean) and "
            "rationale (short sentence)."
            f"\n\nPost Details:\n{post_details}"
        )
        try:
            return _parse_as_model(
                self._openai,
                model=self._model,
                prompt=prompt,
                text_format=InitialAssessment,
                telemetry=self._telemetry,
                prompt_label="initial_assessment",
            )
        except ValidationError as exc:
            return InitialAssessment(
                is_automation=False,
                rationale=f"Parsing error: {exc}",
            )
        except Exception as exc:  # network or OpenAI error
            return InitialAssessment(
                is_automation=False,
                rationale=f"Assessment unavailable ({exc})",
            )

    def deep_assessment(self, full_post: Dict[str, Any]) -> AutomationInsight:
        comments = full_post.get("comments", [])[:5]
        comment_snippets = [
            f"- {_truncate(comment.get('body', ''), 240)}" for comment in comments
        ]
        comments_block = "\n".join(comment_snippets) or "No comments captured."
        body = _truncate(full_post.get("selftext") or "", 1200)
        prompt = (
            f"{self._prompts['deep_assessment']}\n\n"
            "Return structured data with fields automation_summary (one "
            "sentence), deep_analysis (two or three sentences), "
            "automation_complexity (one of: low, medium, high), and "
            "required_tools (list of tools or APIs)."
            f"\n\nTitle: {full_post.get('title')}\n"
            f"Body:\n{body or '[no body]'}\n\n"
            f"Top Comments:\n{comments_block}"
        )
        try:
            return _parse_as_model(
                self._openai,
                model=self._model,
                prompt=prompt,
                text_format=AutomationInsight,
                telemetry=self._telemetry,
                prompt_label="deep_assessment",
            )
        except ValidationError as exc:
            return AutomationInsight(
                automation_summary="Deep assessment failed to parse response.",
                deep_analysis=f"Parsing error: {exc}",
                automation_complexity="unknown",
                required_tools=[],
            )
        except Exception as exc:
            return AutomationInsight(
                automation_summary="Deep assessment unavailable.",
                deep_analysis=f"OpenAI error: {exc}",
                automation_complexity="unknown",
                required_tools=[],
            )

    def analyze_post(
        self, post_summary: Dict[str, Any], *, comment_limit: int
    ) -> PostReport:
        initial = self.initial_assessment(post_summary)
        if initial.is_automation:
            try:
                full_post = fetch_full_post(
                    self._reddit,
                    post_summary["id"],
                    max_comments=comment_limit,
                    telemetry=self._telemetry,
                )
                deep = self.deep_assessment(full_post)
            except Exception as exc:
                deep = AutomationInsight(
                    automation_summary=initial.rationale,
                    deep_analysis=f"Deep assessment unavailable ({exc})",
                    automation_complexity="unknown",
                    required_tools=[],
                )
        else:
            deep = AutomationInsight(
                automation_summary=initial.rationale,
                deep_analysis="Not assessed (initial review not affirmative).",
                automation_complexity="unknown",
                required_tools=[],
            )

        created_dt = datetime.fromtimestamp(
            post_summary["created_utc"], tz=timezone.utc
        )
        created = created_dt.strftime("%Y-%m-%d %H:%M:%S")

        return PostReport(
            submission_id=post_summary["id"],
            subreddit=post_summary["subreddit"],
            title=post_summary["title"],
            url=post_summary["url"],
            permalink=post_summary["permalink"],
            created=created,
            created_utc=created_dt,
            score=post_summary["score"],
            num_comments=post_summary["num_comments"],
            initial_assessment=initial,
            automation_insight=deep,
        )


class AnalysisReport(BaseModel):
    """Container for the complete automation run metadata and results."""

    generated_at: str
    query: str
    time_filter: str
    posts: List[PostReport] = Field(default_factory=list)

    @property
    def total_posts(self) -> int:
        return len(self.posts)

